development:
  adapter: mysql2
  database: hanchor
  host: 127.0.0.1
  encoding: utf8
  username: root
  password: "db"
  pool: 25

test:
  adapter: mysql2
  database: hanchor
  host: 127.0.0.1
  encoding: utf8
  username: root
  password: "db"

production:
  adapter: mysql2
  database: hanchor
  host: 127.0.0.1
  encoding: utf8
  username: root
  password: "db"
